### ISSUE TITLE
E-tube issue, pipinstall

### ISSUE THREAD

**Issue by djmarioka** [Nanxsec/E-tube#1]
Hi,

when doing "pip install .", for E-tube, it says in the CMD line: ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found. 

What should I do?.

Thanks.
![E-TUBE, ISSUE](https://user-images.githubusercontent.com/81478245/115979714-bf162680-a587-11eb-8250-aa0b796756dd.png)

**Comment by Nanxsec** [comment]
Neste caso eu recomendo você a dar esse comando na pasta de Downloads: git
clone https://github.com/lucas-Dk/E-tube

Em seguida entre na pasta do E-tube e digite o comando: pip install -r
requirements.txt e ele irá isntalar o pytube para você

Em seguida você pode abrir o e-tube.py com o comando: python e-tube.py

Obrigado por me enviar um email e me atualize sobre qualquer erro!

- lucas-Dk

Em dom., 25 de abr. de 2021 às 00:33, djmarioka ***@***.***>
escreveu:
